### ISSUE TITLE
Improvement: make use of cpu pipeline easier

### ISSUE THREAD

**Issue by cpezzato** [tud-airlab/mppi-isaac#47]
There is still some leftover hardcoded "cuda:0" here and there. We should make sure that we can run the CPU pipeline by just setting the mppi configuration parameter "device" to CPU.

**Comment by eliatrevisan** [comment]
The IsaacGymWrapper now takes the device (cuda:0) by default. All the _server files pass the device to the IsaacGymWrapper.
