### ISSUE TITLE
When running the benchmarks/panda_arm/run_experiment.sh file, an error message shows that some modules is missing.

### ISSUE THREAD

**Issue by zhe-beginner** [tud-airlab/mppi-isaac#49]
Hello, thank you very much for seeing my difficulties, I would be very grateful if you could help me.
When I run the run_experiment.sh file in benchmarks, the following error message will be generated:

(mppiisaac-py3.8) ljz@ljz-computer:~/mppi-isaac/benchmarks/panda_arm$ ./run_experiment.sh 
pybullet build time: May 20 2022 19:44:17
Importing module 'gym_38' (/home/ljz/mppi-isaac/thirdparty/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/ljz/mppi-isaac/thirdparty/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 2.0.0+cu117
Device count 1
/home/ljz/mppi-isaac/thirdparty/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/ljz/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Emitting ninja build file /home/ljz/.cache/torch_extensions/py38_cu117/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Module forcesProMpcPlanner not found: No module named 'forcespro'
Module acadosMpcPlanner not found: No module named 'acados_template'
Link with name world does not has a parent. Link name is skipped.
Link with name world does not has a parent. Link name is skipped.
/home/ljz/.cache/pypoetry/virtualenvs/mppiisaac-DC-EcHMy-py3.8/lib/python3.8/site-packages/gym/spaces/box.py:78: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Link with name world does not has a parent. Link name is skipped.
Link with name world does not has a parent. Link name is skipped.
Traceback (most recent call last):
  File "/home/ljz/.cache/pypoetry/virtualenvs/mppiisaac-DC-EcHMy-py3.8/bin/runner", line 8, in <module>
    sys.exit(main())
  File "/home/ljz/.cache/pypoetry/virtualenvs/mppiisaac-DC-EcHMy-py3.8/lib/python3.8/site-packages/plannerbenchmark/exec/runner.py", line 201, in main
    myRunner.parseArguments()
  File "/home/ljz/.cache/pypoetry/virtualenvs/mppiisaac-DC-EcHMy-py3.8/lib/python3.8/site-packages/plannerbenchmark/exec/runner.py", line 102, in parseArguments
    planner = PlannerRegistry.create_planner(self._experiment, planner_file)
  File "/home/ljz/.cache/pypoetry/virtualenvs/mppiisaac-DC-EcHMy-py3.8/lib/python3.8/site-packages/plannerbenchmark/generic/planner_registry.py", line 32, in create_planner
    planner = cls.REGISTRY[name]
KeyError: 'forcesprompc'

The general meaning is that the “forcespro” and “acados_template” modules are missing.
But it seems that these modules cannot be installed using “pip install ***”

I would be very grateful if I could get your help.

**Comment by cpezzato** [comment]
Hi, 

This is related to the afct that [ForcesPro](https://www.embotech.com/products/forcespro/overview/) is a commercial software and you need a license for that (if you are a scholar you should get it for free when you request one).

If you cannot get a license then you can run the comparisons only with fabrics. To do so you can run:

`runner -c setup/exp.yaml -p setup/mppi.yaml setup/fabric.yaml -n 10 --res-folder results/series --random-goal --random-obst --render`

This is the same command in `run_experiments.sh` but withou MPC. 

Also, in `setup/exp.yaml` you can set the duration T for your comparison, the current T=1000 is a bit lengthy for fast prototyping

I updated the README [3a98a14](https://github.com/tud-airlab/mppi-isaac/commit/3a98a144bd2a35c9713d20b62d78474d8ed84f84) in the benchmark folder to make this point clear.
