### ISSUE TITLE
How to control a real robotic arm with Isaac-mppi

### ISSUE THREAD

**Issue by dagenCap** [tud-airlab/mppi-isaac#54]
Can you tell me if controlling the real panda robot arm is through the speed controller of that arm? I'm trying to figure out if I can use the same way to control a real UR series arm.

**Comment by cpezzato** [comment]
Hi, I think there would be no problem controlling the UR series arms with velocity control. What we did with the real panda arm was indeed relying on the velocity control of the arm itself, forwarding the control inputs from mppi. You can then read the joint states from the real robot (position and velocities + additional objects and obstacles) and set the tensor in the simulation. You have to do this after applying each control so at the beginning of a rollout.
